<?php

namespace Database\Seeders;

use App\Models\Sale;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SaleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $salesData  = [
            [
            'name' => 'Edi',
            'email' => 'edi@example.com',
            'nik' => '3174091200010001',
            'address' => 'Jl. Raya Sawit No. 10, Bogor',
            'maps' => 'https://goo.gl/maps/abc123',
            'land' => 'Lempung',
            'number' => '6281234567890',
            'price' => 5000,
            'reflaction' => "true",
            'weight' => 12.5,
            'rendemen_id' => 1,
            'user_id' => 1,
            ],
            [
            'name' => 'Yoyok',
            'email' => 'yoyok@example.com',
            'nik' => '3205011500020002',
            'address' => 'Ds. Karang Anyar RT 3 RW 1, Ciamis',
            'maps' => 'https://goo.gl/maps/def456',
            'land' => 'Berpasir',
            'number' => '6282234567891',
            'price' => 5500,
            'reflaction' => "false",
            'weight' => 15.0,
            'rendemen_id' => 1,
            'user_id' => 2,
            ],
            [
            'name' => 'Yon',
            'email' => 'yon@example.com',
            'nik' => '3301052300030003',
            'address' => 'Jl. Kenanga No. 5, Magelang',
            'maps' => 'https://goo.gl/maps/ghi789',
            'land' => 'Gembur',
            'number' => '6285334567892',
            'price' => 4800,
            'reflaction' => "true",
            'weight' => 10.2,
            'rendemen_id' => 2,
            'user_id' => 3,
            ],
            [
            'name' => 'Reban',
            'email' => 'reban@example.com',
            'nik' => '3407020700040004',
            'address' => 'Ds. Mekarsari No. 12, Bantul',
            'maps' => 'https://goo.gl/maps/jkl012',
            'land' => 'Laterit',
            'number' => '6281239876543',
            'price' => 6200,
            'reflaction' => "false",
            'weight' => 13.4,
            'rendemen_id' => 3,
            'user_id' => 4,
            ],
            [
            'name' => 'Sunarto',
            'email' => 'sunarto@example.com',
            'nik' => '3175081800050005',
            'address' => 'Jl. Merdeka No. 8, Depok',
            'maps' => 'https://goo.gl/maps/mno345',
            'land' => 'Humus',
            'number' => '6281112345678',
            'price' => 5300,
            'reflaction' => "true",
            'weight' => 14.8,
            'rendemen_id' => 2,
            'user_id' => 5,
            ],
            [
            'name' => 'Ulil',
            'email' => 'ulil@example.com',
            'nik' => '3276020400060006',
            'address' => 'Jl. Sukasari No. 7, Bandung',
            'maps' => 'https://goo.gl/maps/pqr678',
            'land' => 'Alluvial',
            'number' => '6282223456789',
            'price' => 5100,
            'reflaction' => "false",
            'weight' => 11.7,
            'rendemen_id' => 1,
            'user_id' => 1,
            ],
            [
            'name' => 'Arief Muntoha',
            'email' => 'arief.muntoha@example.com',
            'nik' => '3503030500070007',
            'address' => 'Ds. Sidorejo, Blitar',
            'maps' => 'https://goo.gl/maps/stu901',
            'land' => 'Vulkanik',
            'number' => '6281237894560',
            'price' => 4900,
            'reflaction' => "true",
            'weight' => 16.2,
            'rendemen_id' => 4,
            'user_id' => 2,
            ],
            [
            'name' => 'Eko',
            'email' => 'eko@example.com',
            'nik' => '3578040600080008',
            'address' => 'Jl. Kaliurang KM 12, Sleman',
            'maps' => 'https://goo.gl/maps/vwx234',
            'land' => 'Regosol',
            'number' => '6281312345678',
            'price' => 5600,
            'reflaction' => "false",
            'weight' => 13.8,
            'rendemen_id' => 1,
            'user_id' => 3,
            ],
            [
            'name' => 'Komang Lampung',
            'email' => 'komang.lampung@example.com',
            'nik' => '3375050700090009',
            'address' => 'Jl. Rawa Indah No. 3, Semarang',
            'maps' => 'https://goo.gl/maps/yzb567',
            'land' => 'Laterit',
            'number' => '6281798765432',
            'price' => 4700,
            'reflaction' => "true",
            'weight' => 12.0,
            'rendemen_id' => 2,
            'user_id' => 4,
            ],
            [
            'name' => 'Agus S.T',
            'email' => 'agus.st@example.com',
            'nik' => '3301060800100010',
            'address' => 'Ds. Sukamaju, Purworejo',
            'maps' => 'https://goo.gl/maps/def999',
            'land' => 'Organosol',
            'number' => '6287771234567',
            'price' => 5900,
            'reflaction' => "false",
            'weight' => 14.5,
            'rendemen_id' => 4,
            'user_id' => 5,
            ],
            [
            'name' => 'Yayuk Dwi Rahayu',
            'email' => 'yayuk.dwi.rahayu@example.com',
            'nik' => '3174091200110011',
            'address' => 'Jl. Cempaka No. 9, Yogyakarta',
            'maps' => 'https://goo.gl/maps/xyz123',
            'land' => 'Andosol',
            'number' => '6281123456789',
            'price' => 5200,
            'reflaction' => "true",
            'weight' => 13.1,
            'rendemen_id' => 3,
            'user_id' => 1,
            ],
            [
            'name' => 'Ulul Amri',
            'email' => 'ulul.amri@example.com',
            'nik' => '3205011500220022',
            'address' => 'Ds. Tegalsari RT 2 RW 1, Malang',
            'maps' => 'https://goo.gl/maps/uvw123',
            'land' => 'Latosol',
            'number' => '6282234567892',
            'price' => 5400,
            'reflaction' => "false",
            'weight' => 15.6,
            'rendemen_id' => 1,
            'user_id' => 2,
            ],
            [
            'name' => 'Mukhlis',
            'email' => 'mukhlis@example.com',
            'nik' => '3301052300330033',
            'address' => 'Jl. Melati No. 12, Surabaya',
            'maps' => 'https://goo.gl/maps/opq456',
            'land' => 'Alluvial',
            'number' => '6285334567893',
            'price' => 4950,
            'reflaction' => "true",
            'weight' => 11.9,
            'rendemen_id' => 2,
            'user_id' => 3,
            ],
            [
            'name' => 'Novianto Agus Sulistyo',
            'email' => 'novianto.agus@example.com',
            'nik' => '3407020700440044',
            'address' => 'Ds. Wonosari No. 11, Semarang',
            'maps' => 'https://goo.gl/maps/stu345',
            'land' => 'Andosol',
            'number' => '6281239876544',
            'price' => 6100,
            'reflaction' => "false",
            'weight' => 13.7,
            'rendemen_id' => 3,
            'user_id' => 4,
            ],
            [
            'name' => 'Suran',
            'email' => 'suran@example.com',
            'nik' => '3175081800550055',
            'address' => 'Jl. Gajah Mada No. 3, Jakarta',
            'maps' => 'https://goo.gl/maps/rst789',
            'land' => 'Humus',
            'number' => '6281112345679',
            'price' => 5350,
            'reflaction' => "true",
            'weight' => 14.6,
            'rendemen_id' => 2,
            'user_id' => 5,
            ],
            [
            'name' => 'Purwito',
            'email' => 'purwito@example.com',
            'nik' => '3276020400660066',
            'address' => 'Jl. Srikaya No. 4, Surakarta',
            'maps' => 'https://goo.gl/maps/opq789',
            'land' => 'Lempung',
            'number' => '6282223456790',
            'price' => 5050,
            'reflaction' => "false",
            'weight' => 12.3,
            'rendemen_id' => 1,
            'user_id' => 1,
            ],
            [
            'name' => 'M. Syahroni',
            'email' => 'm.syahroni@example.com',
            'nik' => '3503030500770077',
            'address' => 'Ds. Mulyorejo, Malang',
            'maps' => 'https://goo.gl/maps/uvw456',
            'land' => 'Vulkanik',
            'number' => '6281237894561',
            'price' => 4920,
            'reflaction' => "true",
            'weight' => 16.5,
            'rendemen_id' => 4,
            'user_id' => 2,
            ],
            [
            'name' => 'Asmuni',
            'email' => 'asmuni@example.com',
            'nik' => '3578040600880088',
            'address' => 'Jl. Letjen Suprapto No. 5, Pekanbaru',
            'maps' => 'https://goo.gl/maps/vwx345',
            'land' => 'Regosol',
            'number' => '6281312345679',
            'price' => 5650,
            'reflaction' => "false",
            'weight' => 13.9,
            'rendemen_id' => 1,
            'user_id' => 3,
            ],
            [
            'name' => 'M. Fakhrurozi',
            'email' => 'm.fakhrurozi@example.com',
            'nik' => '3375050700990099',
            'address' => 'Ds. Sumber Rejo, Jember',
            'maps' => 'https://goo.gl/maps/yzb678',
            'land' => 'Laterit',
            'number' => '6281798765433',
            'price' => 4750,
            'reflaction' => "true",
            'weight' => 12.2,
            'rendemen_id' => 2,
            'user_id' => 4,
            ],
            [
            'name' => 'Fauzan Abdillah',
            'email' => 'fauzan.abdillah@example.com',
            'nik' => '3301060800100011',
            'address' => 'Jl. Diponegoro No. 7, Pekalongan',
            'maps' => 'https://goo.gl/maps/def777',
            'land' => 'Organosol',
            'number' => '6287771234568',
            'price' => 5950,
            'reflaction' => "false",
            'weight' => 14.7,
            'rendemen_id' => 4,
            'user_id' => 5,
            ],
        ];

        
        function randomImg()
        {
            $num = rand(1, 10);
            return "singkong{$num}.jpg";
        }

        // Beri 'img' secara random dari singkong1.jpg sampai singkong10.jpg
        foreach ($salesData as &$sale) {
            $sale['img'] = randomImg();
        }

        DB::table('sales')->insert($salesData );
    }
}
